version: 2.1

jobs:
  
  checkout_and_unit_Test:
    docker:
      - image: cimg/node:15.8.0
    steps:
      - checkout
      - run: echo "unit tests"
  deploy_backend:
    machine: true
    steps:
      - run: echo "notifying team of new build pipeline"
  integration_tests_backend:
    machine: true
    steps:
      - run: echo "notifying team of new build pipeline"
  acceptances1:
    machine: true
    steps:
      - run: echo "acceptance tests 6-10"
  acceptances2:
    machine: true
    steps:
      - run: echo "acceptance tests 6-10"
  deployStaging:
    machine: true
    steps:
      - run: echo "deploy staging"
  notifyNewVersion:
    machine: true
    steps:
      - run: echo "notifying client of new version"
  acceptances3:
    machine: true
    steps:
      - run: echo "acceptance tests 1-5"
  checkoutAndTest:
    docker:
      - image: cimg/node:15.8.0
    steps:
      - checkout
      - run: echo "unit tests"
  acceptances4:
    machine: true
    steps:
      - run: echo "acceptance tests 1-5"
  deploy_production:
    docker:
      - image: cimg/node:15.8.0
    steps:
      - checkout
      - run: echo "unit tests"    
workflows:
  build:
    jobs:
      - checkout_and_unit_Test
      - deploy_backend
      - integration_tests_backend
      - deploy_staging
      - deploy_production:
          requires:
            - acceptances1
            - acceptances2
            - acceptances3
            - acceptances4
